### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_att'

### ISSUE THREAD

**Issue by StephenZengCn** [ruotianluo/neuraltalk2.pytorch#12]
`python eval.py --dump_images 0 --num_images 5000 --model topdown/model-best.pth --infos_path topdown/infos_td-best.pkl --language_eval 1 `
```
Traceback (most recent call last):
  File "eval.py", line 109, in <module>
    loader = DataLoader(opt)
  File "/home/demobin/work/github/neuraltalk2.pytorch/dataloader.py", line 42, in __init__
    self.use_att = opt.use_att
AttributeError: 'Namespace' object has no attribute 'use_att'
```

**Comment by StephenZengCn** [comment]
ps:
eval results example
![rst](https://user-images.githubusercontent.com/16394555/29993296-e264688c-8f78-11e7-8644-956a9c2ccb3c.png)

**Comment by ruotianluo** [comment]
Thanks, use_att is a new feature.  Will fix it.

**Comment by ruotianluo** [comment]
My guess is your local cocotalk.json has different vocabulary order from my vocab. Check the latest master, and run the val, see if it fix.
(The evaluation works correctly at my end.)

**Comment by StephenZengCn** [comment]
> Evaluate on Karpathy's test split

this evaluate need download coco dataset and following the preprocessing instructions?

**Comment by ruotianluo** [comment]
no. The test split is part of the standard validation set.

**Comment by StephenZengCn** [comment]
`python eval.py --dump_images 0 --num_images 5000 --model topdown/model-best.pth --infos_path topdown/infos_td-best.pkl --language_eval 1 `
```
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotalk_fc data/cocotalk_att data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "eval.py", line 122, in <module>
    vars(opt))
  File "/home/demobin/work/github/neuraltalk2.pytorch/eval_utils.py", line 82, in eval_split
    data = loader.get_batch(split)
  File "/home/demobin/work/github/neuraltalk2.pytorch/dataloader.py", line 118, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "/home/demobin/work/github/neuraltalk2.pytorch/dataloader.py", line 236, in get
    tmp = self.split_loader.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/demobin/work/github/neuraltalk2.pytorch/dataloader.py", line 182, in __getitem__
    self.use_att
  File "/home/demobin/work/github/neuraltalk2.pytorch/dataloader.py", line 18, in get_npy_data
    return (np.load(fc_file), np.load(att_file)['feat'], ix)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'data/cocotalk_fc/391895.npy'

Terminating BlobFetcher
```

**Comment by StephenZengCn** [comment]
out of following this instruction, because i'm downloading mscoco-2014 train and val dataset
`python scripts/prepro_feats.py --input_json data/dataset_coco.json --output_dir data/cocotalk --images_root $IMAGE_ROOT`

**Comment by ruotianluo** [comment]
I have that file in my folder. Is your prepro_feats.py halted?
