### ISSUE TITLE
Evaluation:  AttributeError: 'Namespace' object has no attribute 'caption_model'

### ISSUE THREAD

**Issue by Leinadho** [ruotianluo/neuraltalk2.pytorch#9]
When running eval.py on python2.7, I get this error: 
`
  File "eval.py", line 99, in <module>
    model = models.setup(opt)
  File "/path/to/neuraltalk2.pytorch/models.py", line 16, in setup
    if opt.caption_model == 'show_tell':
AttributeError: 'Namespace' object has no attribute 'caption_model'
`
It looks like the "caption_model" argument is missing from the Argument Parser in eval.py, causing an error to be thrown when model.py attempts to access it.

**Comment by Leinadho** [comment]
'vocab_size' seems to be missing from opts as well

**Comment by Leinadho** [comment]
And a few opts from ShowTellModel.py (eg: seq_length, drop_prob_lm, etc)

**Comment by ruotianluo** [comment]
You didn't run eval.py with your info.pkl file I guess.

**Comment by Leinadho** [comment]
Hi! I don't think that's the issue, but correct me if I'm mistaken: I did add an info.pkl file, (a custom one and the one which came with your pretrained model) but the problem is with the `opt` variable in eval.py, which is a parser object (so not related to info.pkl...). See lines 71 and 99. 

What I've been doing to fix this is just adding in my own parser arguments to the source. 

So for example, the error says 'No attribute "caption_model", so I add this line: 
`parser.add_argument('--caption_model', type=str, default="show_tell", help='show_tell, show_attend_tell, all_img, fc, att2in, att2in2, adaatt, adaattmo')`
and the error goes away.

**Comment by Leinadho** [comment]
You have this code in eval.py: 

`
71.  opt = parser.parse_args()
72.
73. # Load infos
74.  with open(opt.infos_path) as f:
75.     infos = cPickle.load(f)
...
99. model = models.setup(opt)
`

So it looks to me like the pkl file doesn't affect the models?
Should I pass infos to model instead?

**Comment by ruotianluo** [comment]
ignore = ["id", "batch_size", "beam_size", "start_from", "language_eval"]
for k in vars(infos['opt']).keys():
    if k not in ignore:
        if k in vars(opt):
            assert vars(opt)[k] == vars(infos['opt'])[k], k + ' option not consistent'
        else:
            vars(opt).update({k: vars(infos['opt'])[k]}) # copy over options from model

This part of the code is copying options from the infos.pkl. If you are using the infos.pkl, can you check if caption_model is included in the infos's option.

**Comment by Leinadho** [comment]
Oh, that looks like it could be it, I missed that chunk. 

I'm still a bit confused about the architecture though:
-Is there a list of options that should be included infos.pkl? Do you have instructions for making/using it or should I just figure it out?
-If I'm making my own infos.pkl, how do I know which options to include? (it's not in the readme...maybe it's obvious but I'm slow)
-Should infos.pkl be a parser object, like opts?

I'll need to wait 'till tomorrow (GMT) to check anyway, I don't have access to my machine right now. 
Cheers for the help!

**Comment by ruotianluo** [comment]
Essentially infos.pkl is generated during training. So that the options could match to the training time. There are other stuff like vocabulary are also saved here. It doesn't make sense to me to create a infos by yourself. 
The things in infos that are not necessary for evaluation are validation and training numbers.

**Comment by Leinadho** [comment]
Ok, that's cleared up the initial problem. But now I'm getting a different error:

Traceback (most recent call last):
  File "eval.py", line 100, in <module>
    model.load_state_dict(torch.load(opt.model))
  File "/home/jdu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "q_func.weight" in state_dict'

**Comment by Leinadho** [comment]
There are some [similar problems](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/3) online where the solutions were to edit the key string to a recognised form (eg: removing the q_func prefix). 

Any thoughts on how to fix?

**Comment by Leinadho** [comment]
After printing out the local model state_dict and then the pretrained state_dict, I see that the two "q_func" keys are indeed missing in the model. 

_Sliced output from_ `print(model.state_dict())`
...
), ('logit.weight',
[torch.FloatTensor of size 9488x512]
), ('logit.bias',
[torch.FloatTensor of size 9488]
)])

_Sliced output from_ `print(torch.load(opt.model))`
...
[torch.cuda.FloatTensor of size 9488x512 (GPU 0)]
), ('logit.weight',
[torch.cuda.FloatTensor of size 9488x512 (GPU 0)]
), ('logit.bias',
[torch.cuda.FloatTensor of size 9488 (GPU 0)]
), ('**q_func.weight**',
[torch.cuda.FloatTensor of size 9488x512 (GPU 0)]
), ('**q_func.bias**',
[torch.cuda.FloatTensor of size 9488 (GPU 0)]
)])

Do you know where these are coming from? Why are they in the pretrained model but not the local model?
I think I'll try just manually adding the keys to the local model:
eg: model.state_dict()["q_func.weight"] = torch.cuda.FloatTensor(9488, 512).zero()
      model.state_dict()["q_func.bias"] = torch.cuda.FloatTensor(9488).zero()

**Comment by ruotianluo** [comment]
Sorry, my bad. Just kanually delete the weight and bias.

**Comment by Leinadho** [comment]
Thanks for the help, working fine now!

Here's the code snippet if anyone needs to add it. 
Replace line 100 with this chunk:

`pretrained_states = torch.load(opt.model)
pretrained_states.pop("q_func.weight",0)
pretrained_states.pop("q_func.bias",0)
model.load_state_dict(pretrained_states)`

**Comment by ruotianluo** [comment]
I uploaded a corrected one.
